add method GetFile and refactor code
tucnak/telebot pull request #197
Opened 2019-03-02 19:21 UTC by robatipoor

some time we need work with file in memory not file system

2019-03-02 21:23 UTC, stek29 requested changes

2019-03-02 21:23 UTC, stek29 commented on util.go
> +func get(url string) ([]byte, error) {
I'd suggest a more descriptive name

2019-03-02 21:23 UTC, stek29 commented on bot.go
> +	*file = f
What's the purpose of this assignment?

2019-03-02 21:23 UTC, stek29 commented on bot.go
> +func (b *Bot) GetFile(file *File) ([]byte, error) {
Why won't you reuse GetFile in download?

2019-03-02 21:23 UTC, stek29 commented on bot.go
> +	err = ioutil.WriteFile(localFileName, out, 0644)
Old code was doing io.Copy from resp.Body, and didn't read everything into memory.
I'd say it's a regression.

2019-03-03 13:42 UTC, robatipoor commented
please review pull request again

2019-03-03 19:57 UTC, stek29 approved these changes
lgtm

2019-03-26 13:20 UTC, merged

2019-03-26 13:20 UTC, tucnak commented
Thank you! Sorry for a late merge.