Implement missing parameters of commands-related methods
tucnak/telebot pull request #452
Opened 2021-10-12 09:53 UTC by zry98

Implement the missing two optional parameters (`scope` and `language_code`) of methods `getMyCommands`, `setMyCommands` and `deleteMyCommands` according to the official document: https://core.telegram.org/bots/api#setmycommands.

2022-01-30 12:39 UTC, demget requested changes
This is a significant help, thank you. I left some notes, please fix them and we're happy to merge.

2022-01-30 12:39 UTC, demget commented on options.go
> +const (
Remove `Bot` prefix from constants and all command-related types.

2022-01-30 12:39 UTC, demget commented on options.go
> +	// BotCommandScope types
Move a comment before the `const` declaration.

2022-01-30 12:39 UTC, demget commented on options.go
> +	BotScopeChatMember                   = "chat_member"
It's `CommandScopeChatMember`.

2022-01-30 12:39 UTC, demget commented on options.go
> +	BotCommandScopeChatAdministrators    = "chat_administrators"
Rename to `CommandScopeChatAdmin`.

2022-01-30 12:39 UTC, demget commented on options.go
> +	BotCommandScopeAllChatAdministrators = "all_chat_administrators"
Rename to `CommandScopeAllChatAdmin`.

2022-01-30 19:47 UTC, zry98 commented
OK done, but is there any refactoring plan on method parameters? since there has been a lot of changes in the API, like these command related.

2022-02-04 22:47 UTC, demget commented
Thank you. 

> is there any refactoring plan on method parameters?

What's about them? I see we now fully satisfy Bot API 5.3 changes.

2022-02-05 11:39 UTC, demget approved these changes

2022-02-05 11:40 UTC, merged