Example awslambdaechobot
tucnak/telebot pull request #617
Opened 2023-09-10 10:18 UTC by MetalBlueberry

Hello! This is an awslambdaechobot exmaple that just works. 

I want to put a bit more time into this later so I can explain how every piece in this example works, but for now I would like to know your opinion.

2023-09-10 21:35 UTC, suntong commented on examples/awslambdaechobot/main.go
> +	"gopkg.in/telebot.v3"
This line seems to be redundant and can be removed.

2023-10-16 14:30 UTC, suntong commented
Looks good now. Thanks.

@tucnak, Looks good to you as well?

2023-11-18 16:41 UTC, demget requested changes

2023-11-18 16:41 UTC, demget commented on examples/awslambdaechobot/main.go
> +	"gopkg.in/telebot.v3"
Please add a `tele` alias.

2023-11-18 16:41 UTC, demget commented on examples/awslambdaechobot/destroy.sh
> +curl -H "Content-Type: application/json"  -X POST "https://api.telegram.org/bot$TOKEN/setWebhook" -d "{
Make a one-line:
`curl -H "Content-Type: application/json" -X POST "https://api.telegram.org/bot$TOKEN/setWebhook" -d "{\"url\": \"\" }"`

2023-11-18 16:41 UTC, demget commented on examples/awslambdaechobot/main.go
> +	b.Handle(telebot.OnText, func(ctx telebot.Context) error {
`c tele.Context`

2024-08-09 12:58 UTC, closed without merging