CallBack struct missing some fields
tucnak/telebot pull request #647
Opened 2024-02-03 14:01 UTC by rapour

The telegram Bot API includes `chat_instance` and `game_short_name` in its [CallbackQuery object](https://core.telegram.org/bots/api#callbackquery). Particularly, the `game_short_name` is currently missing in the `Callback` object of the update when a user requests a game's url from the bot and it's also not deserialized in the `Game` object of the callback's message. 

I think it might be nice to have the Callback struct conforming with Telegram's CallbackQuery object and also a lot easier to implement than somehow populating the Game struct in the [message](https://github.com/tucnak/telebot/blob/71ac2995cc5d7379c35fceb3b64ce2c693e79e0c/message.go#L134).

2024-02-20 21:16 UTC, demget requested changes

2024-02-20 21:16 UTC, demget commented on callback.go
> +	// Global identifier, uniquely corresponding to the chat to
Please fix the documentation:

```suggestion
	// ChatInstance is a global identifier, uniquely corresponding to the chat to
```

2024-02-20 21:16 UTC, demget commented on callback.go
> +	// Unique identifier of the game for which a URL is requested
Same here.

2024-02-21 21:56 UTC, rapour commented on callback.go
> +	// Global identifier, uniquely corresponding to the chat to
Done

2024-02-21 21:56 UTC, rapour commented on callback.go
> +	// Unique identifier of the game for which a URL is requested
Done

2024-02-25 11:18 UTC, demget commented
Good catch, thank you for filling the hole in our API.

2024-02-25 11:18 UTC, merged