Feat: add game to the list of inline query results
tucnak/telebot pull request #648
Opened 2024-02-07 11:41 UTC by rapour

[Game](https://core.telegram.org/bots/api#inlinequeryresultgame) is one of the possible types a bot can send as inline query result.

2024-02-20 21:19 UTC, demget requested changes

2024-02-20 21:19 UTC, demget commented on inline_types.go
> +	// Unique identifier of the game.
Documentation

2024-02-20 21:19 UTC, demget commented on inline_types.go
> +	GameShortName string `json:"game_short_name"`
`ShortName`

2024-02-21 22:09 UTC, rapour commented on inline_types.go
> +	// Unique identifier of the game.
Done

2024-02-21 22:09 UTC, rapour commented on inline_types.go
> +	GameShortName string `json:"game_short_name"`
Done

2024-02-25 11:18 UTC, merged