Integration with Business Accounts
tucnak/telebot pull request #706
Opened 2024-06-27 10:52 UTC by Apolisk

2024-06-28 06:52 UTC, Nash-Well requested changes

2024-06-28 06:52 UTC, Nash-Well commented on bot.go
> +func (b *Bot) GetBusinessConnection(businessConnectionID string) (*BusinessConnection, error) {
```go
func (b *Bot) BusinessConnection(connectionID string) (*BusinessConnection, error) {
	params := map[string]string{
		"business_connection_id": connectionID,
	}

	data, err := b.Raw("getBusinessConnection", params)
	if err != nil {
		return nil, err
	}

	var resp struct {
		Result *BusinessConnection
	}

	if err := json.Unmarshal(data, &resp); err != nil {
		return nil, wrapError(err)
	}
	return resp.Result, nil
}
```

2024-06-28 06:52 UTC, Nash-Well commented on message.go
> +	SenderBusinessBot *User `json:"sender_business_bot"`
```go
BusinessBot *User `json:"sender_business_bot"`
```

2024-06-28 06:52 UTC, Nash-Well commented on sticker.go
> +func (b *Bot) ReplaceStickerInSet(of Recipient, name, old_sticker string, sticker InputSticker) (bool, error) {
```go
func (b *Bot) ReplaceStickerInSet(of Recipient, name, oldSticker string, sticker InputSticker) (bool, error) {
	files := make(map[string]File)
	
        repr := sticker.File.process("0", files)
	if repr == "" {
		return false, errors.New("telebot: sticker does not exist")
	}
	sticker.Sticker = repr

	data, err := json.Marshal(sticker)
        if err != nil {
             ...
        }

	params := map[string]string{
		"user_id":     of.Recipient(),
		"name":        name,
		"old_stikcer": oldSticker,
		"sticker":     string(data),
	}

	_, err := b.sendFiles("replaceStickerInSet", files, params)
	return true, err
}
```

2024-07-09 19:09 UTC, sofer-eg commented on sticker.go
> +		"old_stikcer": oldSticker,
"old_sticker": oldSticker,

2024-07-10 07:51 UTC, Apolisk commented on sticker.go
> +		"old_stikcer": oldSticker,
Thank you, already fixed.

2024-08-08 23:34 UTC, merged